### ISSUE TITLE
One UI to many engine

### ISSUE THREAD

**Issue by ymolinet** [wazo-platform/wazo-ui#28]
Is it possible to configure the UI to manage remotly many engine ?

**Comment by sboily** [comment]
nope

**Comment by ymolinet** [comment]
planned ?

**Comment by sboily** [comment]
no, this UI is clearly not developed to use as it.

**Comment by ymolinet** [comment]
So it could be a nice feature, It could be interresting to use it like "phpmyadmin" where you select the server on the login page with the configuration based on an array in the configuration page.

**Comment by sboily** [comment]
Yep but this is not in our plan to develop that in wazo-ui. For us wazo-ui if more a UI toolkit to play with the API of the platform. But PR is welcome.

**Comment by sboily** [comment]
Please open a thread on the forum for the futur. https://wazo-platform.discourse.group.
